fix build on FreeBSD
Since 0.10.6 build on FreeBSD fails with:
p/debug_native.c:1428:24: error: expected ';' after return statement
        if (!buf) {return NULL};