Fix w32 build (cdecl vs stdcall)
error C2440: '=': cannot convert from:
* 'HANDLE (__stdcall *)(DWORD,BOOL,DWORD)'
* 'HANDLE (__cdecl *)(DWORD,BOOL,DWORD)'