Fix compilation error for -D use_libuv=true
Building with -D use_libuv=true results in a compilation error:

    /usr/bin/ld: libr/core/libr_core.so.6.0.9.p/cmd.c.o: in function `session_listen':
    cmd.c:(.text+0x1132ce): undefined reference to `r_core_session_register'
    /usr/bin/ld: libr/core/libr_core.so.6.0.9.p/rtr.c.o: in function `r_core_rtr_http_run':
    rtr.c:(.text+0x2069): undefined reference to `r_core_session_register'

These functions were in the #else of an #if HAVE_LIBUV block and as such
removed by the preprocessor when building with libuv support.

Move them outside of the conditional block to make them available regardless.